// M6-A — Deterministic Mandate Policy Engine
//
// The policy layer converts IntegrityReport evidence (M4 deterministic +
// M5 structured semantic findings) into a single mandate decision:
//
//   ALLOW | REVIEW | PAUSE
//
// It is 100% deterministic and explainable. It NEVER calls an LLM, never asks
// an LLM whether to pause, never parses free-form explanation text, and never
// executes a payment operation. A PAUSE decision is only a determination — the
// actual Razorpay action is implemented separately (not here).

export type MandateDecision = "ALLOW" | "REVIEW" | "PAUSE";

// Structured, explainable reason. `explanation` is GENERATED by the policy from
// structured facts (thresholds, removed keys, percentages) — it is never copied
// from a model's free-form text.
export interface PolicyReason {
  findingType: string;
  dimension: string;
  severity: string;
  explanation: string;
}

export interface PolicyResult {
  decision: MandateDecision;
  reasons: PolicyReason[];
  evaluatedAt: string;
  policyVersion: string;
}

// All thresholds live here — never buried in logic (STEP 3).
export interface IntegrityPolicy {
  policyVersion: string;
  // Price increase (%) below this -> ALLOW.
  priceIncreaseReviewPercent: number;
  // Price increase (%) at or above this -> PAUSE. Between the two -> REVIEW.
  priceIncreasePausePercent: number;
  // If a CRITICAL entitlement is removed, that alone forces PAUSE.
  criticalFindingPauses: boolean;
  // Explicit, documented critical entitlements.
  criticalEntitlements: string[];
  // Semantic degradation with confidence >= this is "high confidence".
  semanticPauseConfidence: number;
}

export const DEFAULT_POLICY: IntegrityPolicy = {
  policyVersion: "mvp-v1",
  priceIncreaseReviewPercent: 5,
  priceIncreasePausePercent: 15,
  criticalFindingPauses: true,
  criticalEntitlements: ["capstone_review", "weekly_mentor_feedback"],
  semanticPauseConfidence: 0.9,
};
